### ISSUE TITLE
  CatalogRequ = requests.get(url = CatalogUrl, headers = headers, cookies = cookies)运行到这里报错

### ISSUE THREAD

**Issue by xilemi** [DragonRollGH/ZhihuZhuanlan#1]

**Comment by DragonRollGH** [comment]
没把cookies复制进去？

**Comment by xilemi** [comment]
> 没把cookies复制进去？

有复制的 cookies都读取到了

**Comment by DragonRollGH** [comment]
发一下错误提示

**Comment by xilemi** [comment]
> 发一下错误提示

  Message='set' object is not subscriptable
  Source=D:\Users\喜乐\Desktop\ZhihuZhuanlan-master\ZhihuZhuanlan.py
  StackTrace:
  File "D:\Users\喜乐\Desktop\ZhihuZhuanlan-master\ZhihuZhuanlan.py", line 20, in <module> (Current frame)
    CatalogRequ = requests.get(url = CatalogUrl, headers = headers, cookies = cookies)

**Comment by DragonRollGH** [comment]
> > 发一下错误提示
> 
> Message='set' object is not subscriptable
> Source=D:\Users\喜乐\Desktop\ZhihuZhuanlan-master\ZhihuZhuanlan.py
> StackTrace:
> File "D:\Users\喜乐\Desktop\ZhihuZhuanlan-master\ZhihuZhuanlan.py", line 20, in (Current frame)
> CatalogRequ = requests.get(url = CatalogUrl, headers = headers, cookies = cookies)

发一下你的程序吧，我运行一下

**Comment by xilemi** [comment]
> > > 发一下错误提示
> > 
> > 
> > Message='set' object is not subscriptable
> > Source=D:\Users\喜乐\Desktop\ZhihuZhuanlan-master\ZhihuZhuanlan.py
> > StackTrace:
> > File "D:\Users\喜乐\Desktop\ZhihuZhuanlan-master\ZhihuZhuanlan.py", line 20, in (Current frame)
> > CatalogRequ = requests.get(url = CatalogUrl, headers = headers, cookies = cookies)
> 
> 发一下你的程序吧，我运行一下

import json
import os

import requests
import pypandoc

ZhuanlanID = '1368221046273925121' #盐选专栏ID

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'}
cookies = {''
    # 浏览器复制Cookies填在此处；Cookies包含个人登录密码，请勿外传。
}

if not os.path.exists(ZhuanlanID):
    os.makedirs(ZhuanlanID)

for offset_i in range(10):
    offset = str(offset_i * 20)
    CatalogUrl = 'https://api.zhihu.com/remix/well/{}/catalog?offset={}&limit=20&order_by=global_idx'.format(ZhuanlanID, offset)
    CatalogRequ = requests.get(url = CatalogUrl, headers = headers, cookies = cookies)
    CatalogDict = json.loads(CatalogRequ.text)
    if not CatalogDict['data']:
        break
    for SectionInfo in CatalogDict['data']:
        SectionIndex = SectionInfo['index']['serial_number_txt']
        SectionTitle = SectionInfo['title']
        SectionID = SectionInfo['id']
        if os.path.exists('{}/{} {}.docx'.format(ZhuanlanID, SectionIndex, SectionTitle)):
            continue
        SectionUrl = 'https://www.zhihu.com/market/paid_column/{}/section/{}'.format(ZhuanlanID, SectionID)
        SectionRequ = requests.get(url = SectionUrl, headers = headers, cookies = cookies)
        with open('temp.html', 'w+', encoding='utf-8') as html:
            html.write(SectionRequ.text)
        pypandoc.convert_file('temp.html', 'docx', outputfile = '{}/{} {}.docx'.format(ZhuanlanID, SectionIndex, SectionTitle))

**Comment by DragonRollGH** [comment]
https://cowtransfer.com/s/d6ad2bd15bf147

**Comment by DragonRollGH** [comment]
https://cowtransfer.com/s/d6ad2bd15bf147
我运行没问题，应该是你填的cookies那几行格式有问题。我把文档上传到这里了你直接下载好了。

**Comment by xilemi** [comment]
> https://cowtransfer.com/s/d6ad2bd15bf147
> 我运行没问题，应该是你填的cookies那几行格式有问题。我把文档上传到这里了你直接下载好了。
谢谢了 可以看下你的cookies填写格式吗

**Comment by DragonRollGH** [comment]
https://cowtransfer.com/s/2e693bf55d294d
我刚才也忘记加cookies了。。刚才上传的不是完整版。
![image](https://user-images.githubusercontent.com/45287374/118220629-b772df00-b4ae-11eb-8df0-dfab3a540e23.png)
从浏览器直接复制的应该是一大段字符串，用
https://gist.github.com/DragonRollGH/09e0ee6d648486e537911209fe19615c
这段代码格式化成字典的形式再放进去

**Comment by xilemi** [comment]
> https://cowtransfer.com/s/2e693bf55d294d
> 我刚才也忘记加cookies了。。刚才上传的不是完整版。
> ![image](https://user-images.githubusercontent.com/45287374/118220629-b772df00-b4ae-11eb-8df0-dfab3a540e23.png)
> 从浏览器直接复制的应该是一大段字符串，用
> https://gist.github.com/DragonRollGH/09e0ee6d648486e537911209fe19615c
> 这段代码格式化成字典的形式再放进去

我按照字典填写的cookie 还是不能下载完整版 是 账号必须是会员吗
